2021-05-23 07:29:58,847:DEBUG:certbot._internal.main:certbot version: 1.15.0
2021-05-23 07:29:58,848:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2021-05-23 07:29:58,848:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/usr/share/nginx/html/letsencrypt', '--email', 'robbyawaldi@gmail.com', '--agree-tos', '--no-eff-email', '--force-renewal', '-d', 'store.robbyawaldi.com']
2021-05-23 07:29:58,848:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2021-05-23 07:29:59,142:DEBUG:certbot._internal.log:Root logging level set at 20
2021-05-23 07:29:59,143:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2021-05-23 07:29:59,154:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2021-05-23 07:29:59,160:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7f30492ae790>
Prep: True
2021-05-23 07:29:59,161:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7f30492ae790> and installer None
2021-05-23 07:29:59,161:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2021-05-23 07:29:59,198:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/124535024', new_authzr_uri=None, terms_of_service=None), 01d8b8c8237b99557f3cc1523af00329, Meta(creation_dt=datetime.datetime(2021, 5, 23, 7, 23, 53, tzinfo=<UTC>), creation_host='5a295c27d822', register_to_eff=None))>
2021-05-23 07:29:59,200:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2021-05-23 07:29:59,202:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2021-05-23 07:30:00,426:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2021-05-23 07:30:00,427:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 23 May 2021 07:30:00 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert",
  "ymPtz37rfF4": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417"
}
2021-05-23 07:30:00,432:DEBUG:certbot.display.util:Notifying user: Requesting a certificate for store.robbyawaldi.com
2021-05-23 07:30:00,481:DEBUG:certbot.crypto_util:Generating RSA key (2048 bits): /etc/letsencrypt/keys/0001_key-certbot.pem
2021-05-23 07:30:00,489:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0001_csr-certbot.pem
2021-05-23 07:30:00,490:DEBUG:acme.client:Requesting fresh nonce
2021-05-23 07:30:00,491:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2021-05-23 07:30:00,734:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2021-05-23 07:30:00,737:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 23 May 2021 07:30:01 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 01046H600wAnXxy-E3q0Zblxgr4KDWBvDD7e-CErVOvOW8E
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2021-05-23 07:30:00,738:DEBUG:acme.client:Storing nonce: 01046H600wAnXxy-E3q0Zblxgr4KDWBvDD7e-CErVOvOW8E
2021-05-23 07:30:00,739:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "store.robbyawaldi.com"\n    }\n  ]\n}'
2021-05-23 07:30:00,742:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTI0NTM1MDI0IiwgIm5vbmNlIjogIjAxMDQ2SDYwMHdBblh4eS1FM3EwWmJseGdyNEtEV0J2REQ3ZS1DRXJWT3ZPVzhFIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIifQ",
  "signature": "lf08gxLT_5x0nepOtNz7dl574hP5CIPrHIpj9Lrk28wfQgeu6rX6qnp9ye9k0VHrtfa-_sgbHIbph-neU9WdOBrdP0Q7QZyY5k6pWN1KhbOSQrBpyTdBz0is3rvR8wABEXs8pFfO6dbrusNI3XqsYkTxdoyS8z0socmf1m3oYL1vYCX5VbjQ49mjr4mDCfOv7gBzTXjlfHNZ1t8sTbCLXfd8NP5MbpO_WTAi6ks6qKC8TrycHmz0LPaWX2oNjNVgqZtYbXZGqvFhjar1XR7NyBxjgmNK0PfVSco8YTDAbqk8YgjMk__vCxuYiPNmvasg6VEfpxz2AGm8pBLo3SRyww",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogInN0b3JlLnJvYmJ5YXdhbGRpLmNvbSIKICAgIH0KICBdCn0"
}
2021-05-23 07:30:00,985:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 429 246
2021-05-23 07:30:00,986:DEBUG:acme.client:Received response:
HTTP 429
Server: nginx
Date: Sun, 23 May 2021 07:30:01 GMT
Content-Type: application/problem+json
Content-Length: 246
Connection: keep-alive
Boulder-Requester: 124535024
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0104hgSJb3aAHb5ZKEOmJRme3sdtn0iK84A2-ULS0VwR6xw

{
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new order :: too many certificates already issued for exact set of domains: store.robbyawaldi.com: see https://letsencrypt.org/docs/rate-limits/",
  "status": 429
}
2021-05-23 07:30:00,987:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/opt/certbot/src/certbot/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1435, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1304, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 140, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 444, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 374, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 406, in _get_order_and_authorizations
    orderr = self.acme.new_order(csr_pem)
  File "/opt/certbot/src/acme/acme/client.py", line 880, in new_order
    return cast(ClientV2, self.client).new_order(csr_pem)
  File "/opt/certbot/src/acme/acme/client.py", line 658, in new_order
    response = self._post(self.directory['newOrder'], order)
  File "/opt/certbot/src/acme/acme/client.py", line 86, in _post
    return self.net.post(*args, **kwargs)
  File "/opt/certbot/src/acme/acme/client.py", line 1198, in post
    return self._post_once(*args, **kwargs)
  File "/opt/certbot/src/acme/acme/client.py", line 1211, in _post_once
    response = self._check_response(response, content_type=content_type)
  File "/opt/certbot/src/acme/acme/client.py", line 1068, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new order :: too many certificates already issued for exact set of domains: store.robbyawaldi.com: see https://letsencrypt.org/docs/rate-limits/
2021-05-23 07:30:00,989:ERROR:certbot._internal.log:An unexpected error occurred:
2021-05-23 07:30:00,991:ERROR:certbot._internal.log:There were too many requests of a given type :: Error creating new order :: too many certificates already issued for exact set of domains: store.robbyawaldi.com: see https://letsencrypt.org/docs/rate-limits/
